routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['locale:tr'])->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifesto', 'HomeController@manifest')->name('manifest');
    Route::get('/maharetlerimiz', 'HomeController@services')->name('services');
    Route::get('/islerimiz', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/islerimiz/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/iletisim', 'HomeController@contact')->name('contact');
    Route::get('/seyir-defteri', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/seyir-defteri/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/seyir-defteri/etiket/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/fiyat-listesi/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['locale:en'])->prefix('en')->name('en.')->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifest', 'HomeController@manifest')->name('manifest');
    Route::get('/craft', 'HomeController@services')->name('services');
    Route::get('/works', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/works/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/contact', 'HomeController@contact')->name('contact');
    Route::get('/journal', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/journal/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/journal/tag/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/price-list/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['auth'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('contactform', 'ContactFormController');
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('blog', 'BlogController');
    Route::resource('work-category', 'WorkCategoryController');
    Route::resource('user', 'UserController');
    Route::resource('media', 'MediaController');
    Route::resource('text', 'TextController');
    Route::resource('proposal', 'ProposalController');
});

app/Models/Portfolio.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

use App\Traits\HasTranslations;

class Portfolio extends Model
{
    use SoftDeletes,
        HasTranslations;

    const PUBLISHED_AT_FORMATS = [
        'YYYY',
        'MMMM YYYY',
        'D MMMM YYYY',
    ];

    public $fillable = [
        'title',
        'slug',
        'body',
        'published_at',
        'published_at_format',
        'view_type_id',
        'description',
        'featured_at',
        'customer_name',
        'link',
        'is_visible',
    ];

    public $dates = [
        'featured_at',
        'published_at',
    ];

    public $appends = [
        'url',
    ];

    public $translatable = [
        'title',
        'slug',
        'body',
        'description',
        'customer_name',
    ];

    public $casts = [
        'is_visible' => 'boolean',
    ];

    public function media()
    {
        return $this->hasMany(Media::class, 'related_id')
            ->relatedTo('portfolio')
            ->orderBy('order_num');
    }

    public function video()
    {
        return $this->hasOne(Media::class, 'related_id')
            ->relatedTo('portfolio-video')
            ->type('video')
            ->orderBy('order_num');
    }

    public function thumbnail()
    {
        return $this->hasOne(Media::class, 'related_id')
            ->relatedTo('portfolio-thumbnail');
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'porfolio_users', 'portfolio_id', 'user_id');
    }

    public function workCategories()
    {
        return $this->belongsToMany(
            WorkCategory::class,
            'porfolio_categories',
            'portfolio_id',
            'work_category_id'
        );
    }

    public function relatedPortfolios()
    {
        return $this->belongsToMany(
            Portfolio::class,
            'portfolio_relations',
            'portfolio_id',
            'related_portfolio_id'
        )->orderBy('order_num', 'asc');
    }

    public function getUrlAttribute(): string
    {
        return ba_route('portfolio.show', $this->slug);
    }
}

app/Http/Controllers/Admin/PortfolioController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\View\View;

use App\Http\Controllers\Controller;
use App\Models\Portfolio;
use App\Services\PortfolioService;
use App\Services\UserService;

class PortfolioController extends Controller
{
    /**
     * @var PortfolioService
     */
    protected $portfolioService;

    /**
     * @var UserService
     */
    protected $userService;

    public function __construct(
        PortfolioService $portfolio,
        UserService $userService
    ) {
        $this->portfolioService = $portfolio;
        $this->userService = $userService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $list = $this->portfolioService->getAdminList(30);

        return view('admin.portfolio.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = $this->userService->getAdminList();
        $categories = $this->portfolioService->getCategoryAdminList();
        $portfolioList = $this->portfolioService->adminAllExcept(new Portfolio());
        $publishedAtFormatList = Portfolio::PUBLISHED_AT_FORMATS;

        return view('admin.portfolio.form', [
            'portfolio' => new Portfolio(),
            'portfolioList' => $portfolioList,
            'publishedAtFormatList' => $publishedAtFormatList,
            'users' => $users,
            'categories' => $categories,
            'lang' => config('app.fallback_locale'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $postData = $request->validate([
            'title' => 'required',
            'body' => 'required',
            'customer_name' => 'required',
            'category_ids' => 'required|array',
            'description' => 'required',
            'user_ids' => 'required|array',
            'media' => 'required|array',
            'media.*' => 'image|mimes:jpeg,png',
            'published_at' => '',
            'published_at_format' => '',
            'thumbnail' => 'required|mimes:jpeg,png',
            'featured_at' => '',
            'link' => '',
            'related_portfolio_ids' => 'array',
            'video' => 'mimes:mp4',
            'view_type_id' => 'required',
        ]);

        $portfolio = $this->portfolioService->save(
            new Portfolio(),
            config('app.fallback_locale'),
            $postData
        );

        return redirect()->to(route('admin.portfolio.edit', $portfolio->id))
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function show(Portfolio $portfolio)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Portfolio $portfolio): View
    {
        $lang = $request->input('lang', config('app.fallback_locale'));
        $users = $this->userService->getAdminList();
        $categories = $this->portfolioService->getCategoryAdminList();
        $portfolioList = $this->portfolioService->adminAllExcept($portfolio);
        $publishedAtFormatList = Portfolio::PUBLISHED_AT_FORMATS;

        return view('admin.portfolio.form', [
            'portfolio' => $portfolio,
            'portfolioList' => $portfolioList,
            'publishedAtFormatList' => $publishedAtFormatList,
            'users' => $users,
            'categories' => $categories,
            'lang' => $lang,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Portfolio $portfolio)
    {
        $postData = $request->validate([
            'title' => 'required|sometimes',
            'body' => 'required|sometimes',
            'customer_name' => 'required|sometimes',
            'category_ids' => 'required|array|sometimes',
            'description' => 'required|sometimes',
            'is_visible' => 'required|boolean|sometimes',
            'user_ids' => 'required|array|sometimes',
            'lang' => 'required|in:' .
                implode(',', config('ba.available_languages')),
            'media' => 'sometimes|array',
            'media.*' => 'sometimes|image|mimes:jpeg,png',
            'published_at' => 'sometimes',
            'published_at_format' => 'sometimes',
            'thumbnail' => 'sometimes|image|mimes:jpeg,png',
            'featured_at' => 'sometimes',
            'link' => 'sometimes',
            'related_portfolio_ids' => 'array|sometimes',
            'video' => 'sometimes|mimes:mp4',
            'view_type_id' => 'sometimes|required',
        ]);

        $this->portfolioService->save($portfolio, $postData['lang'], $postData);

        return redirect()->back()
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Portfolio  $portfolio
     * @return \Illuminate\Http\Response
     */
    public function destroy(Portfolio $portfolio)
    {
        $portfolio->delete();

        return redirect()->back()
            ->with('success', __('Silindi'));
    }
}

resources/views/admin/portfolio/form.blade.php
@extends('layouts.admin')

@section('header')
  <h3>
    {{ $portfolio->id ? $portfolio->title : __('Yeni İş Ekle') }}
    - <em>{{ strtoupper($lang) }}</em>
  </h3>
@endsection

@section('content')
  {!! Form::open([
    'url' => $portfolio->id ? route('admin.portfolio.update', $portfolio->id) : route('admin.portfolio.store'),
    'method' => $portfolio->id ? 'PUT' : 'POST',
    'files' => true,
    ]) !!}

    <input type="hidden" name="lang" value="{{ $lang }}">

    <div class="form-group">
      <label for="title">{{ __('Başlık') }}</label>
      <input
        type="text"
        name="title"
        class="form-control"
        id="title"
        maxlength="150"
        required
        value="{{ old('title') ?: $portfolio->getTranslation('title', $lang, false) }}"
      >
    </div>

    <div class="form-group">
      <label for="description">{{ __('İş tanımı') }}</label>
      <input
        type="text"
        name="description"
        class="form-control"
        id="description"
        maxlength="150"
        required
        value="{{ old('description') ?: $portfolio->getTranslation('description', $lang, false) }}"
      >
    </div>

    <div class="form-group">
      <label for="customer_name">{{ __('Müşteri') }}</label>
      <input
        type="text"
        name="customer_name"
        class="form-control"
        id="customer_name"
        maxlength="150"
        required
        value="{{ old('customer_name') ?: $portfolio->getTranslation('customer_name', $lang, false) }}"
      >
    </div>

    <div class="form-group">
      <label for="category_ids">{{ __('Kategoriler') }}</label>
      <select
        name="category_ids[]"
        class="form-control select2-init"
        id="category_ids"
        required
        multiple
      >
        @foreach($categories as $category)
          <option
            value="{{ $category->id }}"
            @if($portfolio->workCategories and $portfolio->workCategories->contains('id', $category->id)) selected @endif
          >
            {{ $category->title }}
          </option>
        @endforeach
      </select>
    </div>

    <div class="form-group">
      <label for="user_ids">{{ __('Kimler çalıştı?') }}</label>
      <select
        name="user_ids[]"
        class="form-control select2-init"
        id="user_ids"
        required
        multiple
      >
        @foreach($users as $user)
          <option
            value="{{ $user->id }}"
            @if($portfolio->users and $portfolio->users->contains('id', $user->id)) selected @endif
          >
            {{ $user->name }}
          </option>
        @endforeach
      </select>
    </div>

    <div class="form-group">
      <label for="published_at">{{ __('Yayınlanma tarihi') }}</label>
      <input
        type="date"
        name="published_at"
        class="form-control"
        id="published_at"
        value="{{ old('published_at') ?: ($portfolio->published_at ? $portfolio->published_at->format('Y-m-d') : '') }}"
      >
      <p class="help-block">
        İşin yayına girme tarihi. Tam tarih bilinmiyorsa tahmini girilebilir.
      </p>
    </div>

    <div class="form-group">
      <label for="published_at_format">{{ __('Yayın tarihi formatı') }}</label>
      <select
        name="published_at_format"
        class="form-control"
        id="published_at_format"
        value="{{ old('published_at') ?: $portfolio->published_at }}"
      >
        @foreach($publishedAtFormatList as $item)
          <option
            value="{{ $item }}"
            @if($item === (old('published_at_format') ?: $portfolio->published_at_format))
              selected
            @endif
          >{{ __($item) }}</option>
        @endforeach
      </select>
      <p class="help-block">
        İşin yayına girme tarihi. Tam tarih bilinmiyorsa tahmini girilebilir.
      </p>
    </div>

    <div class="form-group">
      <label for="link">{{ __('Bağlantı') }}</label>
      <input
        type="url"
        name="link"
        class="form-control"
        id="link"
        maxlength="1000"
        value="{{ old('link') ?: $portfolio->link }}"
      >
      <p class="help-block">
        Eğer webde bir karşılığı varsa ve aktifse buraya işin bağlantısı girilebilir.
      </p>
    </div>

    <div class="form-group">
      <label for="related_portfolio_ids">{{ __('İlgili işler') }}</label>
      <select
        name="related_portfolio_ids[]"
        class="form-control select2-init"
        id="related_portfolio_ids"
        multiple
      >
        @foreach($portfolioList as $item)
          <option
            value="{{ $item->id }}"
            @if(!empty(old('related_portfolio_ids')))
              @if(in_array($item->id, old('related_portfolio_ids')))
                selected
              @endif
            @elseif(!empty($portfolio->relatedPortfolios))
              @if($portfolio->relatedPortfolios->contains('id', $item->id))
                selected
              @endif
            @endif
          >
            {{ $item->title }} - {{ $item->workCategories->implode('title', ', ') }}
          </option>
        @endforeach
      </select>
      <p class="help-block">
        Yaptığımız diğer işlerden seçilir. Rastgele 3 tanesi gösterilecektir.
      </p>
    </div>

    <div class="form-group">
      <label for="view_type_id">{{ __('Görünüm tipi') }}</label>
      <select
        name="view_type_id"
        class="form-control"
        id="view_type_id"
      >
        @foreach(config('ba.portfolio_types') as $item)
          <option
            value="{{ $item }}"
            @if($item === (old('view_type_id') ?: $portfolio->view_type_id))
              selected
            @endif
          >{{ __('ba.portfolio_view_' . $item) }}</option>
        @endforeach
      </select>
      <p class="help-block">
        Yaptığımız diğer işlerden seçilir. Rastgele 3 tanesi gösterilecektir.
      </p>
    </div>

    <div class="form-group">
      <label for="body">{{ __('Metin') }}</label>
      <textarea
        name="body"
        class="form-control summernote-init"
        id="body"
        required
      >{!! old('body') ?: $portfolio->getTranslation('body', $lang, false) !!}</textarea>
    </div>

    <div class="form-group">
      <label for="thumbnail">{{ __('Küçük resim') }}</label>
      <input
        class="form-control"
        id="thumbnail"
        name="thumbnail"
        type="file"
        accept="image/*"
        @if(empty($portfolio->id))
          required
        @endif
      >
      <p class="help-block">
        Kare olmalı. Sadece bir tane. Listede gözükmesi için.
      </p>
    </div>

    <div class="form-group">
      <label for="media">{{ __('Görseller') }}</label>
      <input
        class="form-control"
        id="media"
        name="media[]"
        type="file"
        accept="image/*"
        multiple
      >
      <p class="help-block">
        Sınırsız ekleyebilirsin. "Kaydet"tiğinde yüklenecek. Vakit alabilir, biraz sabır.
      </p>
    </div>

    <div class="form-group">
      <label for="video">{{ __('Video') }}</label>
      <input
        class="form-control"
        id="video"
        name="video"
        type="file"
        accept="video/mp4"
        multiple
      >
      <p class="help-block">
        Sadece tek bir MP4 yükleyebilirsin. <strong>Çok</strong> vakit alabilir, biraz sabır.
      </p>
    </div>

    <div class="text-right">
      <button type="submit" class="btn btn-outline-primary">{{ __('Kaydet') }}</button>
    </div>

  {!! Form::close() !!}

  @if($portfolio->id and $portfolio->thumbnail)
    <h3>{{ __('Mevcut Küçük Resim') }}</h3>

    <img class="img-fluid" src="{{ $portfolio->thumbnail->url }}">
  @endif

  @if($portfolio->id and $portfolio->media->count())
    <h3>{{ __('Mevcut Görseller') }}</h3>

    <gallery-edit-component
      gallery-json="{!! str_replace('"', '\'', json_encode($portfolio->media->toArray(), JSON_HEX_APOS | JSON_HEX_QUOT)) !!}"
      csrf-token="{{ csrf_token() }}"
    ></gallery-edit-component>

    <!-- <div class="row">
      @foreach($portfolio->media as $media)
        <div class="col-6 col-md-3 mb-3 img-box">
          <img src="{{ $media->url_thumb }}" class="img-fluid">

          {!! Form::open([
            'url' => route('admin.media.destroy', $media->id),
            'method' => 'DELETE',
            ]) !!}
            <button
              type="submit"
              class="btn btn-danger btn-sm"
              data-ask="{{ __('Silmek istediğinden emin misin?') }}"
            ><i class="fas fa-trash"></i></button>
          {!! Form::close() !!}
        </div>
      @endforeach
    </div> -->
  @endif

@endsection

resources/views/admin/portfolio/index.blade.php
@extends('layouts.admin')

@section('header')
  <div class="row">
    <div class="col-12 col-md-8">
      <h3>bagimsizatolye.org yönetici</h3>
    </div>
    <div class="col-12 col-md-4 text-xs-center text-md-right">
      <a class="btn btn-outline-dark" href="{{ route('admin.portfolio.create') }}">
        {{ __('Yeni İş Ekle') }}
      </a>
    </div>
  </div>
@endsection

@section('content')
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 60px;"></th>
        <th>{{ __('Başlık') }}</th>
        <th>{{ __('Kategoriler') }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
        <tr>
          <td>
            @if($item->thumbnail)
              <img src="{{ $item->thumbnail->url_thumb }}" style="height: 30px;">
            @endif
          </td>
          <td><a href="{{ route('portfolio.show', $item->slug) }}">{{ $item->title }}</a></td>
          <td>
            @if($item->workCategories->count() > 0)
              {{ $item->workCategories->pluck('title')->join(', ') }}
            @endif
          </td>
          <td class="text-right">
            {{ Form::open([
              'url' => route('admin.portfolio.update', $item->id),
              'method' => 'PUT',
              'class' => 'd-inline',
              ]) }}
              @if(empty($item->featured_at))
                <input type="hidden" name="featured_at" value="{{ now() }}">
                <input type="hidden" name="lang" value="{{ config('app.locale') }}">
                <button
                  type="submit"
                  class="btn btn-outline-success btn-sm"
                  title="{{ __('Öne çıkar') }}"
                ><i class="far fa-star"></i></button>
              @else
                <input type="hidden" name="featured_at" value="">
                <input type="hidden" name="lang" value="{{ config('app.locale') }}">
                <button
                  type="submit"
                  class="btn btn-success btn-sm"
                  title="{{ __('Öne çıkanlardan kaldır') }}"
                ><i class="fas fa-star"></i></button>
              @endif
            {{ Form::close() }}

            {{ Form::open([
              'url' => route('admin.portfolio.update', $item->id),
              'method' => 'PUT',
              'class' => 'd-inline',
              ]) }}
              @if(!$item->is_visible)
                <input type="hidden" name="is_visible" value="1">
                <input type="hidden" name="lang" value="{{ config('app.locale') }}">
                <button
                  type="submit"
                  class="btn btn-outline-success btn-sm"
                  title="{{ __('Göster') }}"
                ><i class="far fa-eye-slash"></i></button>
              @else
                <input type="hidden" name="is_visible" value="0">
                <input type="hidden" name="lang" value="{{ config('app.locale') }}">
                <button
                  type="submit"
                  class="btn btn-success btn-sm"
                  title="{{ __('Gizle') }}"
                ><i class="far fa-eye"></i></button>
              @endif
            {{ Form::close() }}

            @foreach(config('ba.available_languages') as $lang)
              <a
                class="btn btn-outline-info btn-sm"
                href="{{ route('admin.portfolio.edit', [
                  $item->id,
                  'lang' => $lang,
                  ]) }}"
              >{{ __('Düzenle') }} - <strong>{{ strtoupper($lang) }}</strong></a>
            @endforeach

            {{ Form::open([
              'url' => route('admin.portfolio.destroy', $item->id),
              'method' => 'DELETE',
              'class' => 'd-inline',
              ]) }}
              <button
                type="submit"
                class="btn btn-outline-danger btn-sm"
                data-ask="{{ __('Silmek istediğinden emin misin?') }}"
              >{{ __('Sil') }}</button>
            {{ Form::close() }}
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>

  {{ $list->render() }}

  @if($list->count() === 0)
    <p class="text-center">
      {{ __('Hiçbir şey eklenmemiş.') }}
    </p>
  @endif
@endsection