routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['locale:tr'])->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifesto', 'HomeController@manifest')->name('manifest');
    Route::get('/maharetlerimiz', 'HomeController@services')->name('services');
    Route::get('/islerimiz', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/islerimiz/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/iletisim', 'HomeController@contact')->name('contact');
    Route::get('/seyir-defteri', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/seyir-defteri/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/seyir-defteri/etiket/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/fiyat-listesi/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['locale:en'])->prefix('en')->name('en.')->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifest', 'HomeController@manifest')->name('manifest');
    Route::get('/craft', 'HomeController@services')->name('services');
    Route::get('/works', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/works/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/contact', 'HomeController@contact')->name('contact');
    Route::get('/journal', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/journal/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/journal/tag/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/price-list/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['auth'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('contactform', 'ContactFormController');
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('blog', 'BlogController');
    Route::resource('work-category', 'WorkCategoryController');
    Route::resource('user', 'UserController');
    Route::resource('media', 'MediaController');
    Route::resource('text', 'TextController');
    Route::resource('proposal', 'ProposalController');
});

app/Http/Controllers/Admin/ContactFormController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\ContactForm;
use App\Services\ContactFormService;

class ContactFormController extends Controller
{
    /**
     * @var ContactFormService
     */
    protected $contactFormService;

    public function __construct(ContactFormService $contactFormService)
    {
        $this->contactFormService = $contactFormService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list = $this->contactFormService->getAdminList();

        return view('admin.contact-form.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ContactForm  $contactForm
     * @return \Illuminate\Http\Response
     */
    public function show(ContactForm $contactForm)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\ContactForm  $contactForm
     * @return \Illuminate\Http\Response
     */
    public function edit(ContactForm $contactForm)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\ContactForm  $contactForm
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ContactForm $contactForm)
    {
        $formData = $request->validate([
            'answered_at' => '',
        ]);

        if (!empty($formData['answered_at'])) {
            $formData['answered_at'] = now();
            $formData['answered_by_id'] = auth()->id();
        }

        $this->contactFormService->save($contactForm, $formData);

        return redirect()->back()
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ContactForm  $contactForm
     * @return \Illuminate\Http\Response
     */
    public function destroy(ContactForm $contactForm)
    {
        //
    }
}

resources/views/admin/contact-form/index.blade.php
@extends('layouts.admin')

@section('header')
  <div class="row">
    <div class="col-12">
      <h3>bagimsizatolye.org yönetici</h3>
    </div>
  </div>
@endsection

@section('content')
  <table class="table table-striped table-sm table-responsive-md">
    <caption>
      {{ __('Önce cevap verilmeyenler listelenir. Bunlar da eskiden yeniye doğru sıralanır.') }}
    </caption>
    <thead class="thead-dark">
      <tr>
        <th style="min-width: 150px;">{{ __('İsim') }}</th>
        <th>{{ __('E-posta') }}</th>
        <th>{{ __('Konu') }}</th>
        <th>{{ __('Mesaj') }}</th>
        <th style="min-width: 158px;">{{ __('Cevap') }}</th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
        <tr>
          <td>
            {{ $item->name }}
            <br>
            {{ format_datetime($item->created_at) }}
          </td>
          <td><a href="mailto:{{ $item->email }}">{{ $item->email }}</a></td>
          <td>{{ $item->subject }}</td>
          <td>{{ $item->text }}</td>
          <td>
            @if(!is_null($item->answered_at))
              {{ format_datetime($item->answered_at) }}<br>
              {{ $item->answeredBy->name }}
            @else
              <strong class="text-danger">{{ __('Cevap verilmedi') }}</strong>
              <br><br>
              <form method="post" action="{{ route('admin.contactform.update', $item->id) }}">
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="answered_at" value="{{ now() }}">
                <button class="btn btn-sm btn-primary" type="submit">
                  {{ __('Cevap verildi olarak işaretle') }}
                </button>
              </form>
            @endif
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>

  {{ $list->render() }}

  @if($list->count() === 0)
    <p class="text-center">
      {{ __('Hiçbir şey eklenmemiş.') }}
    </p>
  @endif
@endsection