routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['locale:tr'])->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifesto', 'HomeController@manifest')->name('manifest');
    Route::get('/maharetlerimiz', 'HomeController@services')->name('services');
    Route::get('/islerimiz', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/islerimiz/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/iletisim', 'HomeController@contact')->name('contact');
    Route::get('/seyir-defteri', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/seyir-defteri/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/seyir-defteri/etiket/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/fiyat-listesi/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['locale:en'])->prefix('en')->name('en.')->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifest', 'HomeController@manifest')->name('manifest');
    Route::get('/craft', 'HomeController@services')->name('services');
    Route::get('/works', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/works/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/contact', 'HomeController@contact')->name('contact');
    Route::get('/journal', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/journal/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/journal/tag/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/price-list/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['auth'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('contactform', 'ContactFormController');
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('blog', 'BlogController');
    Route::resource('work-category', 'WorkCategoryController');
    Route::resource('user', 'UserController');
    Route::resource('media', 'MediaController');
    Route::resource('text', 'TextController');
    Route::resource('proposal', 'ProposalController');
});

app/Models/Text.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Authentik\EloquentCache\Cacheable;

class Text extends Model
{
    use Cacheable;

    protected $fillable = [
        'key',
        'value',
        'lang',
    ];

    public function getCacheTTL()
    {
        return 60 * 24;
    }
}

app/Http/Controllers/Admin/TextController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\Text;
use App\Services\TextService;

class TextController extends Controller
{
    /**
     * @var TextService
     */
    protected $textService;

    public function __construct(TextService $textService)
    {
        $this->textService = $textService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $textList = $this->textService->getAdminList();
        $languageProgress = [];

        foreach ($textList as $key => $languageList) {
            if (strpos($key, 'seo_') !== false) {
                continue;
            }

            foreach ($languageList as $langKey => $value) {
                if (!isset($languageProgress[$langKey])) {
                    $languageProgress[$langKey] = [
                        'total' => 0,
                        'completed' => 0,
                        'empty' => 0,
                    ];
                }

                if (empty($value)) {
                    $languageProgress[$langKey]['empty']++;
                } else {
                    $languageProgress[$langKey]['completed']++;
                }

                $languageProgress[$langKey]['total']++;
            }
        }

        return view('admin.text.index', [
            'textList' => $textList,
            'languageProgress' => $languageProgress,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formData = $request->validate([
            'value' => 'required|string|nullable',
            'key' => 'required|string',
            'lang' => 'in:tr,en',
        ]);

        $text = $this->textService->getText($formData['key'], $formData['lang']);

        if (!$text) {
            $text = $this->textService->saveText(
                new Text(),
                $formData['key'],
                $formData['lang'],
                $formData['value']
            );
        } else {
            $text = $this->textService->saveText(
                $text,
                $formData['key'],
                $formData['lang'],
                $formData['value']
            );
        }

        return response()->json($text);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/text/index.blade.php
@extends('layouts.admin')

@section('header')
  <div class="row">
    <div class="col-12 col-md-8">
      <h3>bagimsizatolye.org yönetici</h3>
    </div>
  </div>
@endsection

@section('content')
  <p>
    {{ __('Başlık ve alt başlıklarda kalın yazı için <strong>kalın</strong>.') }}
    <br>
    {{ __('Alt satıra geçmek için: <br> buradan sonrası alt satır.') }}
    <br>
    {{ __('<em>Eğik yazı</em>') }}
    <br>
    {{ __('Bu kodlar sadece başlıklarda ve uzun metinlerde çalışır.') }}
  </p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>{{ __('Metin') }}</th>
        <th>
          {{ __('Türkçe') }}
          <em class="float-right">
            {{ $languageProgress['tr']['completed'] }} /
            {{ $languageProgress['tr']['total'] }}
          </em>
        </th>
        <th>
          {{ __('İngilizce') }}
          <em class="float-right">
            {{ $languageProgress['en']['completed'] }} /
            {{ $languageProgress['en']['total'] }}
          </em>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($textList as $key => $languageList)
        <tr>
          <td>
            {{ __("ba.$key") }}
          </td>
          @foreach($languageList as $languageKey => $value)
            <td>
              <form
                class="text-form"
                method="post"
                action="{{ route('admin.text.store') }}"
              >
                @csrf
                <textarea
                  name="value"
                  class="form-control"
                >{{ $value }}</textarea>
                <input type="hidden" name="lang" value="{{ $languageKey }}">
                <input type="hidden" name="key" value="{{ $key }}">
                <button type="submit" class="d-none"></button>
              </form>
            </td>
          @endforeach
        </tr>
      @endforeach
    </tbody>
  </table>
@endsection