routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['locale:tr'])->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifesto', 'HomeController@manifest')->name('manifest');
    Route::get('/maharetlerimiz', 'HomeController@services')->name('services');
    Route::get('/islerimiz', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/islerimiz/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/iletisim', 'HomeController@contact')->name('contact');
    Route::get('/seyir-defteri', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/seyir-defteri/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/seyir-defteri/etiket/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/fiyat-listesi/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['locale:en'])->prefix('en')->name('en.')->group(function () {
    Auth::routes(['register' => false]);

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/manifest', 'HomeController@manifest')->name('manifest');
    Route::get('/craft', 'HomeController@services')->name('services');
    Route::get('/works', 'HomeController@portfolio')->name('portfolio.index');
    Route::get('/works/{slug}', 'HomeController@portfolioShow')
        ->name('portfolio.show');
    Route::any('/contact', 'HomeController@contact')->name('contact');
    Route::get('/journal', 'HomeController@blogIndex')->name('blog.index');
    Route::get('/journal/{slug}', 'HomeController@blogShow')->name('blog.show');
    Route::get('/journal/tag/{slug}', 'HomeController@tagShow')
        ->name('blog.tag.show');
    Route::get('/price-list/{proposalCode}', 'ProposalController@show')
        ->name('proposal.show');
});

Route::middleware(['auth'])->namespace('Admin')->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', 'AdminController@index')->name('home');
    Route::resource('contactform', 'ContactFormController');
    Route::resource('portfolio', 'PortfolioController');
    Route::resource('blog', 'BlogController');
    Route::resource('work-category', 'WorkCategoryController');
    Route::resource('user', 'UserController');
    Route::resource('media', 'MediaController');
    Route::resource('text', 'TextController');
    Route::resource('proposal', 'ProposalController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use App\Traits\HasTranslations;

class User extends Authenticatable
{
    use Notifiable,
        HasTranslations;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'title',
        'description',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public $translatable = [
        'title',
        'description',
    ];

    public function photo()
    {
        return $this->hasOne(Media::class, 'related_id')
            ->relatedTo('user');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Services\UserService;

class UserController extends Controller
{
    /**
     * @var UserService
     */
    protected $userService;

    public function __construct(
        UserService $userService
    ) {
        $this->userService = $userService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(): View
    {
        $list = $this->userService->getAdminList();

        return view('admin.user.index', [
            'list' => $list,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        return view('admin.user.form', [
            'user' => new User(),
            'lang' => config('app.fallback_locale'),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request): RedirectResponse
    {
        $postData = $request->validate([
            'title' => '',
            'email' => [
                'required',
                'email',
                Rule::unique('users'),
            ],
            'name' => 'required',
            'description' => '',
            'password' => 'nullable|min:6|confirmed',
            'password_confirmation' => 'nullable|min:6|required_with:password',
            'media' => 'required|image|mimes:jpeg,png',
        ]);

        $user = $this->userService->save(
            new User(),
            config('app.fallback_locale'),
            $postData
        );

        return redirect()->to(route('admin.user.edit', $user->id))
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, User $user): View
    {
        $lang = $request->input('lang', config('app.fallback_locale'));

        return view('admin.user.form', [
            'user' => $user,
            'lang' => $lang,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user): RedirectResponse
    {
        $postData = $request->validate([
            'title' => '',
            'email' => [
                'required',
                'email',
                Rule::unique('users')->ignore($user->id),
            ],
            'name' => 'required',
            'description' => '',
            'password' => 'nullable|min:6|confirmed',
            'password_confirmation' => 'nullable|min:6|required_with:password',
            'media' => 'image|mimes:jpeg,png',
            'lang' => 'required|in:' .
                implode(',', config('ba.available_languages')),
        ]);

        if (empty($postData['password'])) {
            unset($postData['password']);
        }

        $this->userService->save($user, $postData['lang'], $postData);

        return redirect()->back()
            ->with('success', __('Kaydedildi'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->back()
            ->with('success', __('Silindi'));
    }
}

resources/views/admin/user/form.blade.php
@extends('layouts.admin')

@section('header')
  <h3>
    {{ $user->id ? $user->name : __('Yeni Kişi Ekle') }}
    - <em>{{ strtoupper($lang) }}</em>
  </h3>
@endsection

@section('content')
  {!! Form::open([
    'url' => $user->id ? route('admin.user.update', $user->id) : route('admin.user.store'),
    'method' => $user->id ? 'PUT' : 'POST',
    'files' => true,
    ]) !!}

    <input type="hidden" name="lang" value="{{ $lang }}">

    <div class="form-group">
      <label for="name">{{ __('İsim') }}</label>
      <input
        type="text"
        name="name"
        class="form-control"
        id="name"
        maxlength="255"
        required
        value="{{ old('name') ?: $user->name }}"
        autocomplete="off"
      >
    </div>

    <div class="form-group">
      <label for="email">{{ __('E-posta') }}</label>
      <input
        type="email"
        name="email"
        class="form-control"
        id="email"
        maxlength="255"
        required
        value="{{ old('email') ?: $user->email }}"
        autocomplete="off"
      >
    </div>

    <div class="form-group">
      <label for="title">{{ __('Unvan') }}</label>
      <input
        type="text"
        name="title"
        class="form-control"
        id="title"
        maxlength="255"
        value="{{ old('title') ?: $user->getTranslation('title', $lang, false) }}"
        autocomplete="off"
      >
    </div>

    <div class="form-group">
      <label for="password">{{ __('Parola') }}</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        maxlength="32"
        value="{{ old('password') }}"
        autocomplete="new-password"
      >
    </div>

    <div class="form-group">
      <label for="password_confirmation">{{ __('Parola tekrar') }}</label>
      <input
        type="password"
        name="password_confirmation"
        class="form-control"
        id="password_confirmation"
        maxlength="32"
        value="{{ old('password_confirmation') }}"
        autocomplete="new-password"
      >
    </div>

    <div class="form-group">
      <label for="description">{{ __('Kısa geçmiş') }}</label>
      <textarea
        name="description"
        class="form-control"
        id="description"
      >{{ old('description') ?: $user->getTranslation('description', $lang, false) }}</textarea>
    </div>

    <div class="form-group">
      <label for="media">{{ __('Görsel') }}</label>
      <input
        class="form-control"
        id="media"
        name="media"
        type="file"
        accept="image/*"
      >
      <p class="help-block">
        Sadece bir tane. Kare olmalı.
      </p>
    </div>

    @if($user->photo)
      <div class="col-12 col-md-6 col-lg-4">
        <img src="{{ $user->photo->url }}" class="img-fluid" alt="{{ $user->name }}">
      </div>
    @endif

    <div class="text-right">
      <button type="submit" class="btn btn-outline-primary">{{ __('Kaydet') }}</button>
    </div>

  {!! Form::close() !!}

@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')

@section('header')
  <div class="row">
    <div class="col-12 col-md-8">
      <h3>{{ __('Biz') }}</h3>
    </div>
    <div class="col-12 col-md-4 text-xs-center text-md-right">
      <a class="btn btn-outline-dark" href="{{ route('admin.user.create') }}">
        {{ __('Yeni Kişi Ekle') }}
      </a>
    </div>
  </div>
@endsection

@section('content')
  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width: 40px;"></th>
        <th>{{ __('İsim') }}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach($list as $item)
        <tr>
          <td>
            @if($item->photo)
              <img src="{{ $item->photo->url_thumb }}" style="max-height: 30px;">
            @endif
          </td>
          <td>{{ $item->name }}</td>
          <td class="text-right">
            @foreach(config('ba.available_languages') as $lang)
              <a
                class="btn btn-outline-info btn-sm"
                href="{{ route('admin.user.edit', [
                  $item->id,
                  'lang' => $lang,
                  ]) }}"
              >{{ __('Düzenle') }} - <strong>{{ strtoupper($lang) }}</strong></a>
            @endforeach
            {{ Form::open([
              'url' => route('admin.user.destroy', $item->id),
              'method' => 'DELETE',
              'class' => 'd-inline',
              ]) }}
              <button type="submit" class="btn btn-outline-danger btn-sm" data-ask="{{ __('Silmek istediğinden emin misin?') }}">
                {{ __('Sil') }}
              </button>
            {{ Form::close() }}
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>

  @if($list->count() === 0)
    <p class="text-center">
      {{ __('Hiçbir şey eklenmemiş.') }}
    </p>
  @endif
@endsection